name: terraform-plan
on:
  pull_request:
    branches:
      - main
jobs:
  plan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Initialize Terraform
        run: |
          cd environments/dev
          terraform init
      - name: Plan
        run: |
          cd environments/dev
          terraform plan -out=plan.out
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: environments/dev/plan.out